"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import {
  FileText,
  Plus,
  Printer,
  Save,
  Trash2,
} from "lucide-react";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { BillDetailsForm } from "@/components/billing/BillDetailsForm";
import { BillItemsTable } from "@/components/billing/BillItemsTable";
import { BillTotals } from "@/components/billing/BillTotals";
import { BillPrintView } from "@/components/billing/BillPrintView";
import { ScannerWindow } from "@/components/scan/ScannerWindow";
import { AlertBanner } from "@/components/ui/AlertBanner";
import { ConfirmDialog } from "@/components/ui/ConfirmDialog";
import { LoadingSpinner } from "@/components/ui/LoadingSpinner";
import { useAuth } from "@/contexts/AuthContext";
import { useBarcodeScan } from "@/hooks/useBarcodeScan";
import { useBilling } from "@/hooks/useBilling";
import { isSupabaseConfigured } from "@/lib/supabase/client";
import type { BillInput } from "@/lib/types/database";

export default function BillingPage() {
  const { can } = useAuth();
  const canCreateBill = can("billing.create");
  const canEditPrice = can("billing.editPrice");

  const {
    bills,
    activeBill,
    loading,
    mutating,
    error,
    alert,
    startNewBill,
    loadBill,
    saveBill,
    scanToBill,
    editItem,
    removeItem,
    finalize,
    removeBill,
    dismissAlert,
  } = useBilling();

  const [priceOverride, setPriceOverride] = useState<number | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<string | null>(null);
  const [showPrint, setShowPrint] = useState(false);
  const processingRef = useRef(false);
  const saveTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const isDraft = activeBill?.status === "DRAFT";
  const isReadonly = !canCreateBill || !isDraft;

  const onBarcodeDetected = useCallback(
    async (barcode: string) => {
      if (!activeBill || !isDraft || !canCreateBill || processingRef.current)
        return;
      processingRef.current = true;
      try {
        const override =
          canEditPrice && priceOverride !== null && priceOverride > 0
            ? priceOverride
            : 0;
        await scanToBill(activeBill.id, barcode, override);
      } finally {
        processingRef.current = false;
      }
    },
    [activeBill, isDraft, canCreateBill, scanToBill, canEditPrice, priceOverride]
  );

  const { isScanning, cameraError, startScanning, stopScanning, scannerElementId } =
    useBarcodeScan({
      onScan: onBarcodeDetected,
      enabled: Boolean(activeBill && isDraft && canCreateBill),
    });

  const handleDetailsChange = useCallback(
    (input: BillInput) => {
      if (!activeBill || isReadonly) return;
      if (saveTimerRef.current) clearTimeout(saveTimerRef.current);
      saveTimerRef.current = setTimeout(() => {
        saveBill(activeBill.id, input);
      }, 600);
    },
    [activeBill, isReadonly, saveBill]
  );

  const handleEditPrice = useCallback(
    (item: { id: string }, price: number) => {
      if (!canEditPrice) return;
      editItem(item.id, { unit_price: price });
    },
    [editItem, canEditPrice]
  );

  const handlePrint = () => {
    setShowPrint(true);
    setTimeout(() => {
      window.print();
      setShowPrint(false);
    }, 300);
  };

  useEffect(() => {
    return () => {
      if (saveTimerRef.current) clearTimeout(saveTimerRef.current);
    };
  }, []);

  if (!isSupabaseConfigured()) {
    return (
      <DashboardLayout title="Billing" subtitle="Stock-out invoices">
        <AlertBanner
          alert={{
            type: "info",
            message: "Configure Supabase in .env.local to use billing.",
          }}
        />
      </DashboardLayout>
    );
  }

  return (
    <DashboardLayout
      title="Billing"
      subtitle={
        canCreateBill
          ? "Scan stocked-out units to build a modifiable, printable invoice"
          : "View finalized bills generated by managers"
      }
      actions={
        <div className="flex items-center gap-2">
          {activeBill && (
            <button
              onClick={handlePrint}
              className="flex items-center gap-2 rounded-xl border border-surface-border px-3 py-2 text-sm text-zinc-400 hover:bg-white/5"
            >
              <Printer className="h-4 w-4" />
              <span className="hidden sm:inline">Print</span>
            </button>
          )}
          {canCreateBill && (
            <button
              onClick={() => startNewBill()}
              disabled={mutating}
              className="flex items-center gap-2 rounded-xl bg-accent px-3 py-2 text-sm font-medium text-white hover:bg-accent-muted disabled:opacity-50"
            >
              <Plus className="h-4 w-4" />
              <span className="hidden sm:inline">New Bill</span>
            </button>
          )}
        </div>
      }
    >
      <div className="mx-auto max-w-6xl space-y-6 animate-fade-in">
        {alert && <AlertBanner alert={alert} onDismiss={dismissAlert} />}

        {loading ? (
          <LoadingSpinner label="Loading bills…" />
        ) : error ? (
          <AlertBanner alert={{ type: "error", message: error }} />
        ) : (
          <div className="grid gap-6 lg:grid-cols-4">
            <div className="space-y-2 lg:col-span-1">
              <h3 className="text-xs font-medium uppercase tracking-wider text-zinc-500">
                Recent Bills
              </h3>
              {bills.length === 0 ? (
                <p className="text-sm text-zinc-500">No bills yet</p>
              ) : (
                <ul className="space-y-1">
                  {bills.map((b) => (
                    <li key={b.id} className="flex gap-1">
                      <button
                        onClick={() => loadBill(b.id)}
                        className={`flex-1 rounded-xl px-3 py-2.5 text-left text-sm transition ${
                          activeBill?.id === b.id
                            ? "bg-accent/15 text-accent"
                            : "text-zinc-400 hover:bg-white/5"
                        }`}
                      >
                        <span className="flex items-center gap-2">
                          <FileText className="h-3.5 w-3.5" />
                          {b.bill_number}
                        </span>
                        <span className="text-xs text-zinc-600">
                          ₹{Number(b.total).toFixed(2)} · {b.status}
                        </span>
                      </button>
                      {canCreateBill && b.status === "DRAFT" && (
                        <button
                          onClick={() => setDeleteTarget(b.id)}
                          className="rounded-xl p-2 text-zinc-500 hover:bg-white/5 hover:text-danger"
                          aria-label="Delete bill"
                        >
                          <Trash2 className="h-4 w-4" />
                        </button>
                      )}
                    </li>
                  ))}
                </ul>
              )}
            </div>

            <div className="space-y-4 lg:col-span-3">
              {!activeBill ? (
                <div className="rounded-2xl border border-dashed border-surface-border bg-surface-raised p-12 text-center">
                  <p className="text-sm text-zinc-400">
                    {canCreateBill
                      ? "Create a new bill or select one from the list"
                      : "Select a bill from the list to view details"}
                  </p>
                  {canCreateBill && (
                    <p className="mt-2 text-xs text-zinc-600">
                      Flow: Stock Out at Scan Station → scan units here to bill
                    </p>
                  )}
                </div>
              ) : (
                <>
                  <div className="flex flex-wrap items-center justify-between gap-2">
                    <div>
                      <h2 className="text-lg font-semibold text-zinc-100">
                        {activeBill.bill_number}
                      </h2>
                      <p className="text-xs text-zinc-500">
                        Status: {activeBill.status}
                      </p>
                    </div>
                    {canCreateBill && isDraft && (
                      <div className="flex gap-2">
                        <button
                          onClick={() =>
                            saveBill(activeBill.id, {
                              customer_name: activeBill.customer_name,
                              customer_phone: activeBill.customer_phone,
                              customer_address: activeBill.customer_address,
                              notes: activeBill.notes,
                              tax_percent: activeBill.tax_percent,
                              discount: activeBill.discount,
                            })
                          }
                          disabled={mutating}
                          className="flex items-center gap-2 rounded-xl border border-surface-border px-3 py-2 text-sm text-zinc-400 hover:bg-white/5"
                        >
                          <Save className="h-4 w-4" />
                          Save
                        </button>
                        <button
                          onClick={() => finalize(activeBill.id)}
                          disabled={mutating || activeBill.bill_items.length === 0}
                          className="rounded-xl bg-success px-3 py-2 text-sm font-medium text-white hover:bg-success-muted disabled:opacity-50"
                        >
                          Finalize Bill
                        </button>
                      </div>
                    )}
                  </div>

                  <BillDetailsForm
                    bill={activeBill}
                    onChange={handleDetailsChange}
                    readonly={isReadonly}
                  />

                  {canCreateBill && isDraft && (
                    <div className="grid gap-4 lg:grid-cols-2">
                      {canEditPrice && (
                        <div>
                          <label className="mb-1.5 block text-xs font-medium uppercase tracking-wider text-zinc-500">
                            Price Override (₹) — optional
                          </label>
                          <input
                            type="number"
                            min={0}
                            step={0.01}
                            value={priceOverride ?? ""}
                            onChange={(e) =>
                              setPriceOverride(
                                e.target.value === ""
                                  ? null
                                  : Number(e.target.value)
                              )
                            }
                            placeholder="Auto from product price"
                            className="w-full rounded-xl border border-surface-border bg-surface-overlay px-4 py-2.5 text-sm text-zinc-100 outline-none focus:border-accent"
                          />
                          <p className="mt-1 text-xs text-zinc-600">
                            Leave empty to use each product&apos;s retail selling
                            price automatically.
                          </p>
                        </div>
                      )}
                      <div
                        className={`rounded-xl border border-surface-border bg-surface-raised p-3 ${!canEditPrice ? "lg:col-span-2" : ""}`}
                      >
                        <p className="text-xs text-zinc-500">
                          {canEditPrice
                            ? "Scan unit barcodes (87…) that were stocked out. Prices default from the product catalog."
                            : "Scan unit barcodes (87…) that were stocked out. Prices are set from the product catalog."}
                        </p>
                      </div>
                      <div className="lg:col-span-2">
                        <ScannerWindow
                          scannerElementId={scannerElementId}
                          isScanning={isScanning}
                          cameraError={cameraError}
                          onStart={startScanning}
                          onStop={stopScanning}
                          disabled={mutating}
                        />
                      </div>
                    </div>
                  )}

                  <BillItemsTable
                    bill={activeBill}
                    onEditPrice={handleEditPrice}
                    onRemove={removeItem}
                    readonly={isReadonly}
                    canEditPrice={canEditPrice}
                  />

                  <BillTotals bill={activeBill} />
                </>
              )}
            </div>
          </div>
        )}
      </div>

      {showPrint && activeBill && (
        <div className="fixed inset-0 z-50 overflow-auto bg-white">
          <BillPrintView bill={activeBill} />
        </div>
      )}

      <ConfirmDialog
        open={Boolean(deleteTarget)}
        onClose={() => setDeleteTarget(null)}
        onConfirm={async () => {
          if (deleteTarget) await removeBill(deleteTarget);
          setDeleteTarget(null);
        }}
        title="Delete Bill"
        message="Delete this draft bill? Scanned units will be unlinked and can be billed again."
        loading={mutating}
      />
    </DashboardLayout>
  );
}
